import bcrypt from 'bcryptjs';

export const DEMO_PASSWORD = 'GovPass@2026';

export async function getSeedData() {
  const salt = await bcrypt.genSalt(10);
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, salt);

  const districts = [
    { id: 'dst-erd', name: 'Erode', state: 'Tamil Nadu', status: 'ACTIVE' },
    { id: 'dst-slm', name: 'Salem', state: 'Tamil Nadu', status: 'ACTIVE' },
    { id: 'dst-cbe', name: 'Coimbatore', state: 'Tamil Nadu', status: 'ACTIVE' },
    { id: 'dst-chn', name: 'Chennai', state: 'Tamil Nadu', status: 'ACTIVE' },
  ];

  const users = [
    {
      id: 'usr-cala-001',
      official_id: 'CALA-TN-001',
      name: 'Demo CALA Officer',
      email: 'cala.erode@bhoomialert.gov.in',
      password_hash: passwordHash,
      role: 'CALA',
      department: 'Land Acquisition',
      state: 'Tamil Nadu',
      district: 'Erode',
      status: 'ACTIVE',
    },
    {
      id: 'usr-pd-001',
      official_id: 'PD-NHAI-001',
      name: 'Demo Project Director',
      email: 'pd.nhai@bhoomialert.gov.in',
      password_hash: passwordHash,
      role: 'PROJECT_DIRECTOR',
      department: 'Project Management',
      state: 'Tamil Nadu',
      district: 'Erode',
      status: 'ACTIVE',
    },
    {
      id: 'usr-rev-001',
      official_id: 'REV-TN-001',
      name: 'Demo Revenue Officer',
      email: 'revenue.erode@bhoomialert.gov.in',
      password_hash: passwordHash,
      role: 'REVENUE_OFFICER',
      department: 'Revenue',
      state: 'Tamil Nadu',
      district: 'Erode',
      status: 'ACTIVE',
    },
    {
      id: 'usr-legal-001',
      official_id: 'LEGAL-TN-001',
      name: 'Demo Legal Officer',
      email: 'legal.erode@bhoomialert.gov.in',
      password_hash: passwordHash,
      role: 'LEGAL_OFFICER',
      department: 'Legal',
      state: 'Tamil Nadu',
      district: 'Erode',
      status: 'ACTIVE',
    },
    {
      id: 'usr-admin-001',
      official_id: 'ADMIN-001',
      name: 'Demo Super Admin',
      email: 'admin@bhoomialert.gov.in',
      password_hash: passwordHash,
      role: 'SUPER_ADMIN',
      department: 'Administration',
      state: 'Tamil Nadu',
      district: 'ALL',
      status: 'ACTIVE',
    },
    // Inactive user for boundary testing
    {
      id: 'usr-inactive-001',
      official_id: 'INACTIVE-TN-001',
      name: 'Demo Inactive Officer',
      email: 'inactive@bhoomialert.gov.in',
      password_hash: passwordHash,
      role: 'CALA',
      department: 'Land Acquisition',
      state: 'Tamil Nadu',
      district: 'Erode',
      status: 'INACTIVE',
    },
  ];

  const projects = [
    {
      id: 'prj-erd-001',
      project_code: 'PRJ-ERD-001',
      project_name: 'Erode Outer Ring Road Expressway (Phase I)',
      authority: 'NHAI',
      state: 'Tamil Nadu',
      district: 'Erode',
      corridor: 'Erode - Perundurai Corridor',
      current_stage: 'Compensation',
      status: 'IN_PROGRESS',
    },
    {
      id: 'prj-erd-002',
      project_code: 'PRJ-ERD-002',
      project_name: 'Bhavani River Bridge & Approach Road Link',
      authority: 'TNRDC',
      state: 'Tamil Nadu',
      district: 'Erode',
      corridor: 'Bhavani - Anthiyur Link',
      current_stage: 'Documentation',
      status: 'IN_PROGRESS',
    },
    {
      id: 'prj-slm-001',
      project_code: 'PRJ-SLM-001',
      project_name: 'Salem Steel Plant Freight Rail Corridor',
      authority: 'Southern Railway',
      state: 'Tamil Nadu',
      district: 'Salem',
      corridor: 'Salem - Omalur Bypass',
      current_stage: 'Planning',
      status: 'IN_PROGRESS',
    },
    {
      id: 'prj-cbe-001',
      project_code: 'PRJ-CBE-001',
      project_name: 'Coimbatore Western Bypass Alignment (Phase II)',
      authority: 'NHAI',
      state: 'Tamil Nadu',
      district: 'Coimbatore',
      corridor: 'Madukkarai - Sulur Bypass',
      current_stage: 'Possession',
      status: 'IN_PROGRESS',
    },
  ];

  const parcels = [
    {
      id: 'pcl-erd-101',
      parcel_code: 'PCL-ERD-101',
      project_id: 'prj-erd-001',
      district: 'Erode',
      village: 'Perundurai',
      current_stage: 'Compensation',
      risk_score: 88,
      risk_level: 'CRITICAL',
      predicted_delay_days: 120,
      litigation_status: 'COURT_STAY',
      compensation_status: 'PENDING',
      documentation_status: 'VERIFIED',
      survey_status: 'COMPLETED',
    },
    {
      id: 'pcl-erd-102',
      parcel_code: 'PCL-ERD-102',
      project_id: 'prj-erd-001',
      district: 'Erode',
      village: 'Vijayamangalam',
      current_stage: 'Possession',
      risk_score: 25,
      risk_level: 'LOW',
      predicted_delay_days: 0,
      litigation_status: 'NO_LITIGATION',
      compensation_status: 'DISBURSED',
      documentation_status: 'COMPLETED',
      survey_status: 'COMPLETED',
    },
    {
      id: 'pcl-erd-103',
      parcel_code: 'PCL-ERD-103',
      project_id: 'prj-erd-001',
      district: 'Erode',
      village: 'Chennimalai',
      current_stage: 'Compensation',
      risk_score: 76,
      risk_level: 'HIGH',
      predicted_delay_days: 75,
      litigation_status: 'NO_LITIGATION',
      compensation_status: 'PENDING_DELAYED',
      documentation_status: 'VERIFIED',
      survey_status: 'COMPLETED',
    },
    {
      id: 'pcl-erd-104',
      parcel_code: 'PCL-ERD-104',
      project_id: 'prj-erd-002',
      district: 'Erode',
      village: 'Modakkurichi',
      current_stage: 'Documentation',
      risk_score: 58,
      risk_level: 'MEDIUM',
      predicted_delay_days: 40,
      litigation_status: 'NO_LITIGATION',
      compensation_status: 'PENDING',
      documentation_status: 'INCOMPLETE',
      survey_status: 'COMPLETED',
    },
    {
      id: 'pcl-erd-105',
      parcel_code: 'PCL-ERD-105',
      project_id: 'prj-erd-001',
      district: 'Erode',
      village: 'Bhavani',
      current_stage: 'Survey',
      risk_score: 65,
      risk_level: 'MEDIUM',
      predicted_delay_days: 50,
      litigation_status: 'NO_LITIGATION',
      compensation_status: 'PENDING',
      documentation_status: 'VERIFIED',
      survey_status: 'BOUNDARY_CONFLICT',
    },
    {
      id: 'pcl-erd-106',
      parcel_code: 'PCL-ERD-106',
      project_id: 'prj-erd-001',
      district: 'Erode',
      village: 'Gobichettipalayam',
      current_stage: 'R&R',
      risk_score: 72,
      risk_level: 'HIGH',
      predicted_delay_days: 60,
      litigation_status: 'NO_LITIGATION',
      compensation_status: 'IN_PROGRESS',
      documentation_status: 'VERIFIED',
      survey_status: 'COMPLETED',
    },
    {
      id: 'pcl-slm-201',
      parcel_code: 'PCL-SLM-201',
      project_id: 'prj-slm-001',
      district: 'Salem',
      village: 'Kamalapuram',
      current_stage: 'Notification',
      risk_score: 82,
      risk_level: 'HIGH',
      predicted_delay_days: 120,
      litigation_status: 'WRIT_PETITION',
      compensation_status: 'PENDING',
      documentation_status: 'OBJECTION_RAISED',
      survey_status: 'IN_PROGRESS',
    },
    {
      id: 'pcl-cbe-301',
      parcel_code: 'PCL-CBE-301',
      project_id: 'prj-cbe-001',
      district: 'Coimbatore',
      village: 'Madukkarai',
      current_stage: 'Documentation',
      risk_score: 55,
      risk_level: 'MEDIUM',
      predicted_delay_days: 45,
      litigation_status: 'NO_LITIGATION',
      compensation_status: 'IN_PROGRESS',
      documentation_status: 'IN_PROGRESS',
      survey_status: 'COMPLETED',
    },
  ];

  const projectAssignments = [
    {
      id: 'pa-001',
      user_id: 'usr-cala-001',
      project_id: 'prj-erd-001',
    },
    {
      id: 'pa-002',
      user_id: 'usr-cala-001',
      project_id: 'prj-erd-002',
    },
    {
      id: 'pa-003',
      user_id: 'usr-pd-001',
      project_id: 'prj-erd-001',
    },
  ];

  const parcelAssignments = [
    {
      id: 'pca-001',
      user_id: 'usr-cala-001',
      parcel_id: 'pcl-erd-101',
    },
    {
      id: 'pca-002',
      user_id: 'usr-cala-001',
      parcel_id: 'pcl-erd-102',
    },
    {
      id: 'pca-003',
      user_id: 'usr-cala-001',
      parcel_id: 'pcl-erd-103',
    },
    {
      id: 'pca-004',
      user_id: 'usr-cala-001',
      parcel_id: 'pcl-erd-104',
    },
    {
      id: 'pca-005',
      user_id: 'usr-cala-001',
      parcel_id: 'pcl-erd-105',
    },
    {
      id: 'pca-006',
      user_id: 'usr-cala-001',
      parcel_id: 'pcl-erd-106',
    },
  ];

  const predictions = [
    {
      id: 'pred-erd-101',
      parcel_id: 'pcl-erd-101',
      project_id: 'prj-erd-001',
      risk_score: 88,
      risk_level: 'CRITICAL',
      predicted_delay_days: 120,
      factors: JSON.stringify([
        { factor: 'High Court Stay Order', impact: 'High', weight: 45, description: 'Interim stay petition active on land valuation.' },
        { factor: 'Disputed Land Title', impact: 'Medium', weight: 25, description: 'Partition dispute among joint pattadhars.' },
      ]),
      explanation: 'Critical acquisition delay predicted due to active High Court stay order on land valuation.',
      model_type: 'DEMO_RULE_ENGINE',
    },
    {
      id: 'pred-erd-103',
      parcel_id: 'pcl-erd-103',
      project_id: 'prj-erd-001',
      risk_score: 76,
      risk_level: 'HIGH',
      predicted_delay_days: 75,
      factors: JSON.stringify([
        { factor: 'Compensation Disbursement Pending', impact: 'High', weight: 40, description: 'Statutory compensation pending beyond 90 days.' },
      ]),
      explanation: 'High delay risk driven by statutory compensation disbursement pending beyond 90 days.',
      model_type: 'DEMO_RULE_ENGINE',
    },
    {
      id: 'pred-erd-104',
      parcel_id: 'pcl-erd-104',
      project_id: 'prj-erd-002',
      risk_score: 58,
      risk_level: 'MEDIUM',
      predicted_delay_days: 40,
      factors: JSON.stringify([
        { factor: 'Incomplete Revenue Patta Documentation', impact: 'Medium', weight: 35, description: 'Pattadhar succession certificate pending.' },
      ]),
      explanation: 'Moderate delay due to missing landholder identity records and pending title verification.',
      model_type: 'DEMO_RULE_ENGINE',
    },
    {
      id: 'pred-erd-105',
      parcel_id: 'pcl-erd-105',
      project_id: 'prj-erd-001',
      risk_score: 65,
      risk_level: 'MEDIUM',
      predicted_delay_days: 50,
      factors: JSON.stringify([
        { factor: 'Survey Boundary Discrepancy', impact: 'Medium', weight: 38, description: 'Discrepancy with adjoining village FMB sketch.' },
      ]),
      explanation: 'Delays predicted due to boundary conflict with neighboring revenue village.',
      model_type: 'DEMO_RULE_ENGINE',
    },
    {
      id: 'pred-erd-106',
      parcel_id: 'pcl-erd-106',
      project_id: 'prj-erd-001',
      risk_score: 72,
      risk_level: 'HIGH',
      predicted_delay_days: 60,
      factors: JSON.stringify([
        { factor: 'R&R Resettlement Grievance', impact: 'High', weight: 42, description: 'Family rehabilitation package review pending.' },
      ]),
      explanation: 'Acquisition delayed due to pending rehabilitation scheme notification and family objections.',
      model_type: 'DEMO_RULE_ENGINE',
    },
  ];

  const now = new Date();
  const dateOffset = (days: number) => new Date(now.getTime() + days * 86400000).toISOString();

  const interventions = [
    {
      id: 'int-demo-001',
      intervention_code: 'INT-2026-0001',
      parcel_id: 'pcl-erd-101',
      project_id: 'prj-erd-001',
      prediction_id: 'pred-erd-101',
      intervention_type: 'LEGAL_REVIEW',
      title: 'Legal Review Required',
      description: 'Active litigation is contributing significantly to predicted acquisition delay.',
      priority: 'CRITICAL',
      responsible_department: 'Legal',
      responsible_role: 'LEGAL_OFFICER',
      recommended_action: 'Prioritize legal review, verify current litigation status, and identify the next required legal action.',
      status: 'PENDING_REVIEW',
      created_by: 'usr-cala-001',
      approved_by: null,
      approved_at: null,
      due_date: dateOffset(7),
      completed_at: null,
      rejection_reason: null,
      completion_notes: null,
      delay_avoided_days: null,
      outcome_indicator: null,
    },
    {
      id: 'int-demo-002',
      intervention_code: 'INT-2026-0002',
      parcel_id: 'pcl-erd-103',
      project_id: 'prj-erd-001',
      prediction_id: 'pred-erd-103',
      intervention_type: 'COMPENSATION_REVIEW',
      title: 'Compensation Verification Required',
      description: 'Compensation disbursement pending duration exceeds statutory threshold.',
      priority: 'HIGH',
      responsible_department: 'Revenue',
      responsible_role: 'REVENUE_OFFICER',
      recommended_action: 'Verify pending compensation documentation and identify the next release/processing action.',
      status: 'APPROVED',
      created_by: 'usr-cala-001',
      approved_by: 'usr-cala-001',
      approved_at: dateOffset(-2),
      due_date: dateOffset(5),
      completed_at: null,
      rejection_reason: null,
      completion_notes: null,
      delay_avoided_days: null,
      outcome_indicator: null,
    },
    {
      id: 'int-demo-003',
      intervention_code: 'INT-2026-0003',
      parcel_id: 'pcl-erd-105',
      project_id: 'prj-erd-001',
      prediction_id: 'pred-erd-105',
      intervention_type: 'SURVEY_REVERIFICATION',
      title: 'Survey / Boundary Re-verification Required',
      description: 'Identified survey boundary discrepancy with adjoining village.',
      priority: 'MEDIUM',
      responsible_department: 'Revenue',
      responsible_role: 'REVENUE_OFFICER',
      recommended_action: 'Conduct field verification and resolve the identified survey or boundary discrepancy.',
      status: 'IN_PROGRESS',
      created_by: 'usr-cala-001',
      approved_by: 'usr-cala-001',
      approved_at: dateOffset(-4),
      due_date: dateOffset(-1), // Due date in the past -> Overdue!
      completed_at: null,
      rejection_reason: null,
      completion_notes: null,
      delay_avoided_days: null,
      outcome_indicator: null,
    },
    {
      id: 'int-demo-004',
      intervention_code: 'INT-2026-0004',
      parcel_id: 'pcl-erd-106',
      project_id: 'prj-erd-001',
      prediction_id: 'pred-erd-106',
      intervention_type: 'RNR_REVIEW',
      title: 'R&R Review Required',
      description: 'Rehabilitation and resettlement objection lodged by project affected families.',
      priority: 'HIGH',
      responsible_department: 'Land Acquisition',
      responsible_role: 'CALA',
      recommended_action: 'Review rehabilitation and resettlement issue and update pending actions.',
      status: 'ESCALATED',
      created_by: 'usr-cala-001',
      approved_by: 'usr-cala-001',
      approved_at: dateOffset(-5),
      due_date: dateOffset(2),
      completed_at: null,
      rejection_reason: null,
      completion_notes: null,
      delay_avoided_days: null,
      outcome_indicator: null,
    },
    {
      id: 'int-demo-005',
      intervention_code: 'INT-2026-0005',
      parcel_id: 'pcl-erd-104',
      project_id: 'prj-erd-002',
      prediction_id: 'pred-erd-104',
      intervention_type: 'DOCUMENTATION_VERIFICATION',
      title: 'Documentation Verification Required',
      description: 'Missing revenue patta records resolved and verified in coordination with Tahsildar.',
      priority: 'MEDIUM',
      responsible_department: 'Land Acquisition',
      responsible_role: 'CALA',
      recommended_action: 'Verify missing acquisition documentation and update the document completion status.',
      status: 'COMPLETED',
      created_by: 'usr-cala-001',
      approved_by: 'usr-cala-001',
      approved_at: dateOffset(-10),
      due_date: dateOffset(-3),
      completed_at: dateOffset(-1),
      rejection_reason: null,
      completion_notes: 'All missing patta documents verified with Tahsildar office. Registry clearance complete.',
      delay_avoided_days: 25,
      outcome_indicator: 'RESOLVED',
    },
  ];

  const interventionEvents = [
    {
      id: 'evt-001',
      intervention_id: 'int-demo-001',
      event_type: 'INTERVENTION_RECOMMENDED',
      previous_status: null,
      new_status: 'PENDING_REVIEW',
      performed_by: 'usr-cala-001',
      note: 'Rule-Based SOP Recommendation generated based on active Court Stay Order.',
    },
    {
      id: 'evt-002',
      intervention_id: 'int-demo-002',
      event_type: 'INTERVENTION_RECOMMENDED',
      previous_status: null,
      new_status: 'PENDING_REVIEW',
      performed_by: 'usr-cala-001',
      note: 'Rule-Based SOP Recommendation generated.',
    },
    {
      id: 'evt-003',
      intervention_id: 'int-demo-002',
      event_type: 'APPROVED',
      previous_status: 'PENDING_REVIEW',
      new_status: 'APPROVED',
      performed_by: 'usr-cala-001',
      note: 'CALA reviewed and approved compensation verification.',
    },
    {
      id: 'evt-004',
      intervention_id: 'int-demo-003',
      event_type: 'DISPATCHED',
      previous_status: 'APPROVED',
      new_status: 'DISPATCHED',
      performed_by: 'usr-cala-001',
      note: 'Dispatched to Revenue Department.',
    },
    {
      id: 'evt-005',
      intervention_id: 'int-demo-003',
      event_type: 'IN_PROGRESS',
      previous_status: 'DISPATCHED',
      new_status: 'IN_PROGRESS',
      performed_by: 'usr-rev-001',
      note: 'Field revenue team initiated re-survey with FMB sketch.',
    },
    {
      id: 'evt-006',
      intervention_id: 'int-demo-004',
      event_type: 'ESCALATED',
      previous_status: 'IN_PROGRESS',
      new_status: 'ESCALATED',
      performed_by: 'usr-cala-001',
      note: 'Escalated by CALA due to persistent community objections.',
    },
    {
      id: 'evt-007',
      intervention_id: 'int-demo-005',
      event_type: 'COMPLETED',
      previous_status: 'IN_PROGRESS',
      new_status: 'COMPLETED',
      performed_by: 'usr-cala-001',
      note: 'Documentation verified with Tahsildar. Outcome recorded.',
    },
  ];

  const notifications = [
    {
      id: 'notif-001',
      user_id: 'usr-cala-001',
      intervention_id: 'int-demo-001',
      title: 'New Critical Intervention Pending Review',
      message: 'Critical parcel PCL-ERD-101 requires legal review approval.',
      notification_type: 'INTERVENTION_RECOMMENDED',
      is_read: false,
    },
    {
      id: 'notif-002',
      user_id: 'usr-rev-001',
      intervention_id: 'int-demo-002',
      title: 'Intervention Approved for Execution',
      message: 'Compensation verification for PCL-ERD-103 approved and assigned to Revenue Department.',
      notification_type: 'INTERVENTION_APPROVED',
      is_read: false,
    },
    {
      id: 'notif-003',
      user_id: 'usr-cala-001',
      intervention_id: 'int-demo-004',
      title: 'Intervention Escalated',
      message: 'R&R review for PCL-ERD-106 was escalated by CALA.',
      notification_type: 'INTERVENTION_ESCALATED',
      is_read: true,
    },
  ];

  return {
    districts,
    users,
    projects,
    parcels,
    projectAssignments,
    parcelAssignments,
    predictions,
    interventions,
    interventionEvents,
    notifications,
  };
}

