/**
 * BhoomiAlert AI — Stage-Wise Delay Risk Prediction Engine
 *
 * ARCHITECTURE:
 * Project Data
 *      ↓
 * Data Validation (Check presence of stage-specific verified fields)
 *      ↓
 * Stage Feature Preparation (Isolate stage features without leakage)
 *      ↓
 * Stage Prediction (Planning / Land Acquisition / Compensation)
 *      ↓
 * SHAP Explanation (Per-stage factor importance breakdown)
 *      ↓
 * Rule-Based Next Actions (Stage-targeted recommendations)
 *
 * CRITICAL DATA INTEGRITY RULES:
 * 1. Missing stage fields (e.g. PPPIN live source) MUST result in 'NOT ASSESSED' and delayProbability = null.
 * 2. Never convert missing values or nulls to 0 or 0%.
 * 3. Never use overall project delay as land-acquisition delay.
 * 4. Overall coverage is 'INCOMPLETE' if any stage lacks sufficient data; 'NOT ASSESSED' is NEVER treated as LOW risk.
 * 5. SHAP is explanation-only, never a predictor.
 * 6. Recommendations are generated by rule-based logic based on active stage factors.
 */

import {
  StageRiskAssessment,
  ProjectStageRiskResponse,
  ShapContribution,
} from '../types';

/**
 * Parses date string in common Indian / international formats safely:
 * DD-MM-YYYY, DD/MM/YYYY, YYYY-MM-DD
 */
function parseDateSafe(rawDate?: string | number | Date | null): Date | null {
  if (!rawDate) return null;
  if (rawDate instanceof Date && !isNaN(rawDate.getTime())) return rawDate;
  if (typeof rawDate === 'number') {
    const d = new Date(rawDate);
    return isNaN(d.getTime()) ? null : d;
  }

  const str = String(rawDate).trim();
  if (!str) return null;

  const dmyMatch = str.match(/^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$/);
  if (dmyMatch) {
    const day = parseInt(dmyMatch[1], 10);
    const month = parseInt(dmyMatch[2], 10) - 1;
    const year = parseInt(dmyMatch[3], 10);
    const d = new Date(year, month, day);
    return isNaN(d.getTime()) ? null : d;
  }

  const ymdMatch = str.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/);
  if (ymdMatch) {
    const year = parseInt(ymdMatch[1], 10);
    const month = parseInt(ymdMatch[2], 10) - 1;
    const day = parseInt(ymdMatch[3], 10);
    const d = new Date(year, month, day);
    return isNaN(d.getTime()) ? null : d;
  }

  const standard = new Date(str);
  return isNaN(standard.getTime()) ? null : standard;
}

// -----------------------------------------------------------------------------
// STAGE 1 — PLANNING STAGE PREDICTION
// -----------------------------------------------------------------------------
export function evaluatePlanningStage(project: Record<string, any>): StageRiskAssessment {
  const availableFields: string[] = [];
  const missingFields: string[] = [];

  // 1. Feature Collection (ONLY verified planning fields)
  const sector = project.sector || project.subSector || project.projectType;
  if (sector) availableFields.push('sector');
  else missingFields.push('sector');

  const cost = Number(project.estimatedCostCr ?? project.totalProjectCost ?? project.cost);
  const hasCost = !isNaN(cost) && cost > 0;
  if (hasCost) availableFields.push('estimatedCostCr');
  else missingFields.push('estimatedCostCr');

  const location = project.district || project.taluk || project.village || project.locationName;
  if (location) availableFields.push('location');
  else missingFields.push('location');

  const awardDate = parseDateSafe(project.awardDate || project.dateOfAward || project.sanctionedDate);
  const plannedCompletion = parseDateSafe(project.plannedCompletion || project.expectedCompletion);
  if (awardDate || plannedCompletion) availableFields.push('sanctionedDuration');
  else missingFields.push('sanctionedDuration');

  const status = String(project.status || project.currentStage || '').trim();
  if (status) availableFields.push('projectStatus');

  const rawApproval = project.approvalProgress ?? project['Approval Progress'];
  const hasExplicitApproval = rawApproval !== undefined && rawApproval !== null && !isNaN(Number(rawApproval));
  if (hasExplicitApproval) availableFields.push('approvalProgress');

  const rawDoc = project.documentationProgress ?? project['Documentation Progress'];
  const hasExplicitDoc = rawDoc !== undefined && rawDoc !== null && !isNaN(Number(rawDoc));
  if (hasExplicitDoc) availableFields.push('documentationProgress');

  const surveyStatus = project.surveyStatus || project.rawRecord?.surveyStatus;
  if (surveyStatus) availableFields.push('surveyStatus');

  // Minimum required planning features
  if (availableFields.length < 2) {
    return {
      stage: 'Planning',
      status: 'INSUFFICIENT_DATA',
      riskLevel: 'NOT ASSESSED',
      delayProbability: null,
      factors: ['Not Assessed — Insufficient Stage Data (Baseline project planning metrics missing)'],
      recommendation: 'Record baseline planning parameters (sanctioned budget, award date, and sector classification).',
      shapContributions: [],
      insufficientDataReason: 'Insufficient planning-stage attributes provided in project record.',
      dataCoverage: { availableFields, missingFields },
    };
  }

  // 2. Feature Scoring & Factor Analysis
  let planningScore = 20; // Baseline low friction
  const factors: string[] = [];
  const shapRaw: { factor: string; points: number; isPositive: boolean; desc: string }[] = [];

  // A. Capital Scale Complexity
  if (hasCost) {
    if (cost >= 1500) {
      planningScore += 26;
      factors.push(`Mega-scale capital outlay (> ₹1,500 Cr: ₹${cost.toLocaleString()} Cr)`);
      shapRaw.push({
        factor: 'Capital Outlay Scale',
        points: 26,
        isPositive: true,
        desc: `High capital outlay (₹${cost.toLocaleString()} Cr) requires extensive inter-departmental fiscal sanctions.`,
      });
    } else if (cost >= 750) {
      planningScore += 16;
      factors.push(`Substantial capital outlay (₹${cost.toLocaleString()} Cr)`);
      shapRaw.push({
        factor: 'Capital Outlay Scale',
        points: 16,
        isPositive: true,
        desc: `Medium-high capital outlay (₹${cost.toLocaleString()} Cr) increases sanction oversight.`,
      });
    } else {
      shapRaw.push({
        factor: 'Capital Outlay Scale',
        points: -6,
        isPositive: false,
        desc: `Moderate project scale (₹${cost.toLocaleString()} Cr) falls under standard departmental sanctions.`,
      });
    }
  }

  // B. Sector Right-of-Way Complexity
  const sectorStr = String(sector || '').toLowerCase();
  if (
    sectorStr.includes('port') ||
    sectorStr.includes('waterway') ||
    sectorStr.includes('expressway') ||
    sectorStr.includes('coastal')
  ) {
    planningScore += 22;
    factors.push(`High corridor complexity sector (${sector})`);
    shapRaw.push({
      factor: 'Sector Alignment Complexity',
      points: 22,
      isPositive: true,
      desc: `Sector (${sector}) involves complex environmental, coastal zone, or multi-modal right-of-way clearances.`,
    });
  } else if (sectorStr.includes('road') || sectorStr.includes('highway') || sectorStr.includes('rail')) {
    planningScore += 14;
    factors.push(`Linear corridor sector (${sector})`);
    shapRaw.push({
      factor: 'Sector Alignment Complexity',
      points: 14,
      isPositive: true,
      desc: `Linear infrastructure alignment requires continuous longitudinal corridor clearances.`,
    });
  } else {
    shapRaw.push({
      factor: 'Sector Alignment Complexity',
      points: -5,
      isPositive: false,
      desc: `Sector (${sector || 'General'}) has localized site footprint with standard statutory clearances.`,
    });
  }

  // C. Sanctioned Duration & Timeline Window
  if (awardDate && plannedCompletion) {
    const durationMonths = (plannedCompletion.getTime() - awardDate.getTime()) / (1000 * 60 * 60 * 24 * 30.4375);
    const now = new Date();
    const elapsedMonths = (now.getTime() - awardDate.getTime()) / (1000 * 60 * 60 * 24 * 30.4375);

    if (durationMonths > 48) {
      planningScore += 15;
      factors.push(`Extended sanctioned execution horizon (${Math.round(durationMonths)} months)`);
      shapRaw.push({
        factor: 'Sanctioned Duration Window',
        points: 15,
        isPositive: true,
        desc: `Multi-year horizon (${Math.round(durationMonths)} months) introduces inflation and alignment risk.`,
      });
    } else if (elapsedMonths > durationMonths && durationMonths > 0) {
      planningScore += 20;
      factors.push('Project execution duration has exceeded original sanctioned completion timeline');
      shapRaw.push({
        factor: 'Sanctioned Duration Window',
        points: 20,
        isPositive: true,
        desc: 'Elapsed duration exceeds initial sanction schedule.',
      });
    } else {
      shapRaw.push({
        factor: 'Sanctioned Duration Window',
        points: -4,
        isPositive: false,
        desc: 'Planned duration within normal operational bandwidth.',
      });
    }
  }

  // D. Statutory Clearance / Approval Status (if present)
  if (hasExplicitApproval) {
    const appr = Number(rawApproval);
    if (appr < 50) {
      planningScore += 18;
      factors.push(`Statutory clearance progress is lagging (${appr}%)`);
      shapRaw.push({
        factor: 'Statutory Approval Progress',
        points: 18,
        isPositive: true,
        desc: `Low statutory approvals (${appr}%) directly constrain pre-construction handoff.`,
      });
    } else if (appr > 80) {
      planningScore -= 10;
      shapRaw.push({
        factor: 'Statutory Approval Progress',
        points: -10,
        isPositive: false,
        desc: `High statutory approvals (${appr}%) accelerates pre-construction milestones.`,
      });
    }
  }

  // E. Survey Status (if present)
  if (surveyStatus) {
    const surveyStr = String(surveyStatus).toLowerCase();
    if (surveyStr.includes('pending') || surveyStr.includes('delayed') || surveyStr.includes('in progress')) {
      planningScore += 12;
      factors.push(`Cadastral field survey status: ${surveyStatus}`);
      shapRaw.push({
        factor: 'Cadastral Survey Readiness',
        points: 12,
        isPositive: true,
        desc: `Unfinished cadastral survey delays boundary demarcation.`,
      });
    } else if (surveyStr.includes('completed') || surveyStr.includes('done')) {
      planningScore -= 8;
      shapRaw.push({
        factor: 'Cadastral Survey Readiness',
        points: -8,
        isPositive: false,
        desc: `Completed cadastral survey provides verified boundary coordinates.`,
      });
    }
  }

  const boundedScore = Math.max(10, Math.min(96, Math.round(planningScore)));
  const riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' =
    boundedScore >= 70 ? 'HIGH' : boundedScore >= 40 ? 'MEDIUM' : 'LOW';

  if (factors.length === 0) {
    factors.push('Standard planning parameters with manageable alignment complexity');
  }

  // Rule-based planning recommendation
  let recommendation = 'Proceed with standard planning oversight and coordinate regular inter-departmental reviews.';
  if (boundedScore >= 70) {
    recommendation =
      'Convene High-Level Empowered Committee (HLEC) to expedite statutory clearances and finalize alignment frozen zones.';
  } else if (boundedScore >= 40) {
    recommendation =
      'Complete pending inter-departmental documentation and finalize joint cadastral verification with Revenue authorities.';
  }

  // SHAP Feature Importance normalization
  const totalAbsolute = shapRaw.reduce((acc, s) => acc + Math.abs(s.points), 0) || 1;
  const shapContributions: ShapContribution[] = shapRaw.map((s) => ({
    factor: s.factor,
    percentage: Math.round((Math.abs(s.points) / totalAbsolute) * boundedScore),
    isPositive: s.isPositive,
    impactCategory: Math.abs(s.points) >= 18 ? 'High' : Math.abs(s.points) >= 10 ? 'Medium' : 'Low',
    description: s.desc,
  }));

  return {
    stage: 'Planning',
    status: 'ASSESSED',
    riskLevel,
    delayProbability: boundedScore,
    factors,
    recommendation,
    shapContributions,
    dataCoverage: { availableFields, missingFields },
  };
}

// -----------------------------------------------------------------------------
// STAGE 2 — LAND ACQUISITION STAGE PREDICTION
// -----------------------------------------------------------------------------
export function evaluateLandAcquisitionStage(project: Record<string, any>): StageRiskAssessment {
  const availableFields: string[] = [];
  const missingFields: string[] = [];

  // 1. Strictly check genuine land-acquisition specific fields
  const rawAcqProg =
    project.acquisitionProgress ??
    project.landAcquisitionProgressPercent ??
    project['Land Acquisition Progress %'] ??
    project['Acquisition Progress'] ??
    project['acquisition_progress'];

  const hasAcqProgress =
    rawAcqProg !== undefined &&
    rawAcqProg !== null &&
    String(rawAcqProg).trim() !== '' &&
    !isNaN(Number(rawAcqProg));

  if (hasAcqProgress) availableFields.push('acquisitionProgress');
  else missingFields.push('acquisitionProgress');

  const rawCourtCases =
    project.courtCases ??
    project.legalDisputes ??
    project['Court Cases'] ??
    project['Legal Disputes'] ??
    project['court_cases'];

  const hasCourtCases =
    rawCourtCases !== undefined &&
    rawCourtCases !== null &&
    String(rawCourtCases).trim() !== '' &&
    !isNaN(Number(rawCourtCases));

  if (hasCourtCases) availableFields.push('courtCases');
  else missingFields.push('courtCases');

  const rrStatus =
    project.rrStatus ??
    project.rrProgress ??
    project['R&R Status'] ??
    project['R&R Progress'] ??
    project['rr_progress'];

  const hasRr = rrStatus !== undefined && rrStatus !== null && String(rrStatus).trim() !== '';
  if (hasRr) availableFields.push('rrStatus');
  else missingFields.push('rrStatus');

  const rawSurveyStatus =
    project.surveyStatus ?? project['Survey Status'] ?? project['survey_status'];
  const hasSurvey =
    rawSurveyStatus !== undefined &&
    rawSurveyStatus !== null &&
    String(rawSurveyStatus).trim() !== '';
  if (hasSurvey) availableFields.push('surveyStatus');

  const laStartDate = parseDateSafe(
    project.landAcquisitionStartDate ||
    project['Land Acquisition Start Date'] ||
    project.laStartDate
  );
  const laPlannedDate = parseDateSafe(
    project.plannedLandAcquisitionCompletionDate ||
    project['Planned LA Completion Date'] ||
    project.laPlannedCompletionDate
  );
  const laActualDate = parseDateSafe(
    project.actualLandAcquisitionCompletionDate ||
    project['Actual LA Completion Date'] ||
    project.laActualCompletionDate
  );

  const hasLaDates = Boolean(laStartDate || (laPlannedDate && laActualDate));
  if (hasLaDates) availableFields.push('landAcquisitionDates');
  else missingFields.push('landAcquisitionDates');

  // CRITICAL INTEGRITY CHECK:
  // If land acquisition fields are not genuinely present in the record (such as PPPIN official records):
  // Return NOT ASSESSED. Do NOT fabricate or default missing to 0.
  if (!hasAcqProgress && !hasCourtCases && !hasRr && !hasLaDates) {
    return {
      stage: 'Land Acquisition',
      status: 'INSUFFICIENT_DATA',
      riskLevel: 'NOT ASSESSED',
      delayProbability: null,
      factors: [
        'Not Assessed — Insufficient Stage Data',
        'Land-specific records (Acquisition %, Court cases, Survey status) are unavailable in the source data.',
      ],
      recommendation:
        'Upload departmental land acquisition survey data (via CSV/Excel) to activate Land Acquisition stage prediction.',
      shapContributions: [],
      insufficientDataReason:
        'Land-acquisition specific metrics are not published in live PPPIN infrastructure records.',
      dataCoverage: { availableFields, missingFields },
    };
  }

  // 2. Compute Land Acquisition Risk when data is genuinely available
  let acqScore = 30;
  const factors: string[] = [];
  const shapRaw: { factor: string; points: number; isPositive: boolean; desc: string }[] = [];

  // A. Acquisition Progress Shortfall
  if (hasAcqProgress) {
    const prog = Number(rawAcqProg);
    const shortfall = 100 - prog;
    if (prog < 40) {
      acqScore += 35;
      factors.push(`Severe land acquisition lag (Only ${prog}% acquired, ${shortfall}% remaining)`);
      shapRaw.push({
        factor: 'Acquisition Progress Deficit',
        points: 35,
        isPositive: true,
        desc: `Physical possession achieved for only ${prog}% of required alignment.`,
      });
    } else if (prog < 70) {
      acqScore += 20;
      factors.push(`Moderate land acquisition progress (${prog}% acquired)`);
      shapRaw.push({
        factor: 'Acquisition Progress Deficit',
        points: 20,
        isPositive: true,
        desc: `Partial land handover at ${prog}%, right-of-way gaps remain unaddressed.`,
      });
    } else if (prog >= 90) {
      acqScore -= 20;
      shapRaw.push({
        factor: 'Acquisition Progress Deficit',
        points: -20,
        isPositive: false,
        desc: `Substantial land possession achieved (${prog}%), near complete handoff.`,
      });
    } else {
      shapRaw.push({
        factor: 'Acquisition Progress Deficit',
        points: 5,
        isPositive: true,
        desc: `Steady acquisition at ${prog}%.`,
      });
    }
  }

  // B. Court Cases & Legal Injunctions
  if (hasCourtCases) {
    const disputes = Number(rawCourtCases);
    if (disputes >= 10) {
      acqScore += 30;
      factors.push(`Critical litigation barrier (${disputes} active court petitions / stay orders)`);
      shapRaw.push({
        factor: 'Legal & Court Petitions',
        points: 30,
        isPositive: true,
        desc: `${disputes} active court petitions pending before Land Acquisition, Rehabilitation & Resettlement Authority.`,
      });
    } else if (disputes >= 4) {
      acqScore += 18;
      factors.push(`Active legal disputes (${disputes} cases)`);
      shapRaw.push({
        factor: 'Legal & Court Petitions',
        points: 18,
        isPositive: true,
        desc: `${disputes} legal disputes requiring revenue arbitration hearings.`,
      });
    } else if (disputes === 0) {
      acqScore -= 10;
      shapRaw.push({
        factor: 'Legal & Court Petitions',
        points: -10,
        isPositive: false,
        desc: 'Zero litigations or stay orders against land acquisition parcels.',
      });
    }
  }

  // C. R&R Progress
  if (hasRr) {
    const rrVal = Number(rrStatus);
    if (!isNaN(rrVal)) {
      if (rrVal < 50) {
        acqScore += 15;
        factors.push(`Rehabilitation & Resettlement (R&R) lagging at ${rrVal}%`);
        shapRaw.push({
          factor: 'R&R Package Progress',
          points: 15,
          isPositive: true,
          desc: `R&R execution at ${rrVal}% delays eviction and resettlement colony handover.`,
        });
      } else if (rrVal >= 80) {
        acqScore -= 10;
        shapRaw.push({
          factor: 'R&R Package Progress',
          points: -10,
          isPositive: false,
          desc: `R&R resettlement colony implementation well-advanced at ${rrVal}%.`,
        });
      }
    } else {
      const rrStr = String(rrStatus).toLowerCase();
      if (rrStr.includes('pending') || rrStr.includes('delayed') || rrStr.includes('disputed')) {
        acqScore += 15;
        factors.push(`R&R status: ${rrStatus}`);
        shapRaw.push({
          factor: 'R&R Package Progress',
          points: 15,
          isPositive: true,
          desc: `R&R package issues noted: ${rrStatus}.`,
        });
      }
    }
  }

  // D. Land-Specific Date Slippage (ONLY from land-specific dates, never overall project delay)
  if (laPlannedDate && laActualDate) {
    const delayMonths = (laActualDate.getTime() - laPlannedDate.getTime()) / (1000 * 60 * 60 * 24 * 30.4375);
    if (delayMonths > 6) {
      acqScore += 20;
      factors.push(`Land acquisition deadline exceeded by ${Math.round(delayMonths)} months`);
      shapRaw.push({
        factor: 'Land Schedule Overrun',
        points: 20,
        isPositive: true,
        desc: `Dedicated land milestone passed target date by ${Math.round(delayMonths)} months.`,
      });
    }
  }

  const boundedScore = Math.max(10, Math.min(98, Math.round(acqScore)));
  const riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' =
    boundedScore >= 70 ? 'HIGH' : boundedScore >= 40 ? 'MEDIUM' : 'LOW';

  let recommendation = 'Continue routine field revenue verification and track monthly boundary markers.';
  if (boundedScore >= 70) {
    recommendation =
      'Convene Special CALA Review under DRO/Collector; fast-track hearings for contested parcels and expedite R&R settlement.';
  } else if (boundedScore >= 40) {
    recommendation =
      'Prioritize revenue village level settlement camps and resolve pending award objections under Section 28.';
  }

  const totalAbsolute = shapRaw.reduce((acc, s) => acc + Math.abs(s.points), 0) || 1;
  const shapContributions: ShapContribution[] = shapRaw.map((s) => ({
    factor: s.factor,
    percentage: Math.round((Math.abs(s.points) / totalAbsolute) * boundedScore),
    isPositive: s.isPositive,
    impactCategory: Math.abs(s.points) >= 20 ? 'High' : Math.abs(s.points) >= 12 ? 'Medium' : 'Low',
    description: s.desc,
  }));

  return {
    stage: 'Land Acquisition',
    status: 'ASSESSED',
    riskLevel,
    delayProbability: boundedScore,
    factors,
    recommendation,
    shapContributions,
    dataCoverage: { availableFields, missingFields },
  };
}

// -----------------------------------------------------------------------------
// STAGE 3 — COMPENSATION STAGE PREDICTION
// -----------------------------------------------------------------------------
export function evaluateCompensationStage(project: Record<string, any>): StageRiskAssessment {
  const availableFields: string[] = [];
  const missingFields: string[] = [];

  // 1. Strictly check compensation-specific verified fields
  const compensationStatus =
    project.compensationStatus ||
    project['Compensation Status'] ||
    project['compensation_status'];

  const hasStatus = compensationStatus && String(compensationStatus).trim() !== '';
  if (hasStatus) availableFields.push('compensationStatus');
  else missingFields.push('compensationStatus');

  const rawPendingDays =
    project.pendingCompensationDays ??
    project['Pending Compensation Days'] ??
    project['pending_compensation_days'];

  const hasPendingDays =
    rawPendingDays !== undefined &&
    rawPendingDays !== null &&
    String(rawPendingDays).trim() !== '' &&
    !isNaN(Number(rawPendingDays));

  if (hasPendingDays) availableFields.push('pendingCompensationDays');
  else missingFields.push('pendingCompensationDays');

  const rawCompProg =
    project.compensationProgress ??
    project['Compensation Progress'] ??
    project['compensation_progress'];

  const hasCompProg =
    rawCompProg !== undefined &&
    rawCompProg !== null &&
    String(rawCompProg).trim() !== '' &&
    !isNaN(Number(rawCompProg));

  if (hasCompProg) availableFields.push('compensationProgress');

  const rawTotalComp = project.compensation ?? project.totalCompensation ?? project['Compensation'];
  const rawCompPaid = project.compensationPaid ?? project['Compensation Paid'];
  const rawCompPending = project.compensationPending ?? project['Compensation Pending'];
  const hasCompFinancials = Boolean(
    (rawTotalComp && !isNaN(Number(rawTotalComp))) ||
    (rawCompPaid && !isNaN(Number(rawCompPaid))) ||
    (rawCompPending && !isNaN(Number(rawCompPending)))
  );

  if (hasCompFinancials) availableFields.push('compensationFinancials');
  else missingFields.push('compensationFinancials');

  // CRITICAL INTEGRITY CHECK:
  // If compensation fields are absent (e.g. PPPIN live source):
  // Return NOT ASSESSED with delayProbability: null. Do NOT show 0%.
  if (!hasStatus && !hasPendingDays && !hasCompProg && !hasCompFinancials) {
    return {
      stage: 'Compensation',
      status: 'INSUFFICIENT_DATA',
      riskLevel: 'NOT ASSESSED',
      delayProbability: null,
      factors: [
        'Not Assessed — Insufficient Stage Data',
        'Compensation status and disbursement records are unavailable in the source data.',
      ],
      recommendation:
        'Upload verified compensation disbursement rolls (PFMS/e-Treasury records) to activate Compensation stage prediction.',
      shapContributions: [],
      insufficientDataReason:
        'Compensation disbursement metrics are not published in live PPPIN infrastructure records.',
      dataCoverage: { availableFields, missingFields },
    };
  }

  // 2. Compute Compensation Risk when data is genuinely present
  let compScore = 25;
  const factors: string[] = [];
  const shapRaw: { factor: string; points: number; isPositive: boolean; desc: string }[] = [];

  // A. Pending Compensation Days
  if (hasPendingDays) {
    const days = Number(rawPendingDays);
    if (days >= 90) {
      compScore += 35;
      factors.push(`Severe disbursement pendency (${days} days average delay)`);
      shapRaw.push({
        factor: 'Disbursement Pendency Period',
        points: 35,
        isPositive: true,
        desc: `Compensation awards overdue by ${days} days, risking landowner litigation.`,
      });
    } else if (days >= 30) {
      compScore += 18;
      factors.push(`Moderate disbursement delay (${days} days pending)`);
      shapRaw.push({
        factor: 'Disbursement Pendency Period',
        points: 18,
        isPositive: true,
        desc: `Awards pending disbursement for ${days} days.`,
      });
    } else if (days <= 14) {
      compScore -= 10;
      shapRaw.push({
        factor: 'Disbursement Pendency Period',
        points: -10,
        isPositive: false,
        desc: `Prompt processing with average pendency under 14 days.`,
      });
    }
  }

  // B. Compensation Disbursement Progress
  let effProg = hasCompProg ? Number(rawCompProg) : null;
  if (effProg === null && rawTotalComp && rawCompPaid && Number(rawTotalComp) > 0) {
    effProg = Math.round((Number(rawCompPaid) / Number(rawTotalComp)) * 100);
  }

  if (effProg !== null) {
    const shortfall = 100 - effProg;
    if (effProg < 45) {
      compScore += 30;
      factors.push(`Major compensation shortfall (Only ${effProg}% disbursed, ${shortfall}% pending)`);
      shapRaw.push({
        factor: 'Disbursement Progress Deficit',
        points: 30,
        isPositive: true,
        desc: `Only ${effProg}% of total compensation award deposited to affected titleholders.`,
      });
    } else if (effProg < 75) {
      compScore += 15;
      factors.push(`Partial compensation disbursement (${effProg}% paid)`);
      shapRaw.push({
        factor: 'Disbursement Progress Deficit',
        points: 15,
        isPositive: true,
        desc: `Compensation progress at ${effProg}%.`,
      });
    } else if (effProg >= 90) {
      compScore -= 18;
      shapRaw.push({
        factor: 'Disbursement Progress Deficit',
        points: -18,
        isPositive: false,
        desc: `Over ${effProg}% compensation successfully disbursed.`,
      });
    }
  }

  // C. Compensation Status string
  if (hasStatus) {
    const statusStr = String(compensationStatus).toLowerCase();
    if (statusStr.includes('disputed') || statusStr.includes('litigation') || statusStr.includes('delayed')) {
      compScore += 20;
      factors.push(`Compensation audit status flagged: ${compensationStatus}`);
      shapRaw.push({
        factor: 'Title Verification Friction',
        points: 20,
        isPositive: true,
        desc: `Title or share verification bottlenecks flagged under status: ${compensationStatus}.`,
      });
    } else if (statusStr.includes('cleared') || statusStr.includes('completed') || statusStr.includes('disbursed')) {
      compScore -= 12;
      shapRaw.push({
        factor: 'Title Verification Friction',
        points: -12,
        isPositive: false,
        desc: 'Compensation disbursement verified without title flags.',
      });
    }
  }

  const boundedScore = Math.max(10, Math.min(96, Math.round(compScore)));
  const riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' =
    boundedScore >= 70 ? 'HIGH' : boundedScore >= 40 ? 'MEDIUM' : 'LOW';

  let recommendation = 'Maintain DBT queue reconciliation and monitor bank confirmation receipts.';
  if (boundedScore >= 70) {
    recommendation =
      'Initiate emergency compensation disbursal camps; escalate treasury sanctions and establish escrow for disputed titles.';
  } else if (boundedScore >= 40) {
    recommendation =
      'Audit pending bank accounts and clear Section 19 award notices for uncollected entitlements.';
  }

  const totalAbsolute = shapRaw.reduce((acc, s) => acc + Math.abs(s.points), 0) || 1;
  const shapContributions: ShapContribution[] = shapRaw.map((s) => ({
    factor: s.factor,
    percentage: Math.round((Math.abs(s.points) / totalAbsolute) * boundedScore),
    isPositive: s.isPositive,
    impactCategory: Math.abs(s.points) >= 20 ? 'High' : Math.abs(s.points) >= 12 ? 'Medium' : 'Low',
    description: s.desc,
  }));

  return {
    stage: 'Compensation',
    status: 'ASSESSED',
    riskLevel,
    delayProbability: boundedScore,
    factors,
    recommendation,
    shapContributions,
    dataCoverage: { availableFields, missingFields },
  };
}

// -----------------------------------------------------------------------------
// OVERALL EVALUATOR
// -----------------------------------------------------------------------------
export function calculateStageWiseRisk(project: Record<string, any>): ProjectStageRiskResponse {
  const projectId = String(project.projectId || project.id || 'LA-UNKNOWN');
  const projectName = String(project.projectName || project.name || `Project ${projectId}`);

  const planning = evaluatePlanningStage(project);
  const landAcquisition = evaluateLandAcquisitionStage(project);
  const compensation = evaluateCompensationStage(project);

  const stages = [planning, landAcquisition, compensation];
  const assessedStages = stages.filter((s) => s.status === 'ASSESSED');
  const assessedCount = assessedStages.length;
  const totalStages = 3;

  const isComplete = assessedCount === totalStages;
  const overallCoverage: 'COMPLETE' | 'INCOMPLETE' = isComplete ? 'COMPLETE' : 'INCOMPLETE';

  let overallDelayProbability: number | null = null;
  let overallRiskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'NOT ASSESSED' = 'NOT ASSESSED';

  if (isComplete) {
    // When all 3 stages assessed: Weighted aggregation
    // Planning: 25%, Land Acquisition: 45%, Compensation: 30%
    const pProb = planning.delayProbability ?? 50;
    const laProb = landAcquisition.delayProbability ?? 50;
    const cProb = compensation.delayProbability ?? 50;

    const aggregate = Math.round(0.25 * pProb + 0.45 * laProb + 0.30 * cProb);
    overallDelayProbability = Math.max(10, Math.min(98, aggregate));
    overallRiskLevel =
      overallDelayProbability >= 70 ? 'HIGH' : overallDelayProbability >= 40 ? 'MEDIUM' : 'LOW';
  } else if (assessedCount > 0) {
    // If incomplete, provide average of ASSESSED stages only, but keep overallCoverage = INCOMPLETE
    const sum = assessedStages.reduce((acc, s) => acc + (s.delayProbability || 0), 0);
    overallDelayProbability = Math.round(sum / assessedCount);
    overallRiskLevel =
      overallDelayProbability >= 70 ? 'HIGH' : overallDelayProbability >= 40 ? 'MEDIUM' : 'LOW';
  }

  return {
    projectId,
    projectName,
    overallCoverage,
    assessedCount,
    totalStages,
    overallRiskLevel,
    overallDelayProbability,
    planning,
    landAcquisition,
    compensation,
    timestamp: new Date().toISOString(),
  };
}
